API key, secure connections, and further small changes to Elastic connection wrapper
qdrant/vector-db-benchmark pull request #103
Opened 2024-03-04 12:41 UTC by filipecosta90

This PR enables to properly benchmark remote hosts with Elastic, and passing either a secure connection detail or an api key. 
It removes the usage/forcing of http on the benchmark.

2024-03-07 13:53 UTC, KShivendu requested changes
I'm not sure if we want to bother about auth and API keys because we don't benchmark cloud deployments. Will think about this.

2024-03-07 13:53 UTC, KShivendu commented on engine/clients/elasticsearch/config.py
> +    }
```suggestion
    init_params = {
        "verify_certs": False,
        "request_timeout": ELASTIC_TIMEOUT,
        "retry_on_timeout": True,
        **connection_params,
    }
```

2024-03-07 13:53 UTC, KShivendu commented on engine/clients/elasticsearch/config.py
> +    return client
```suggestion
    if ELASTIC_API_KEY is None:
        return Elasticsearch(
            url,
            basic_auth=(ELASTIC_USER, ELASTIC_PASSWORD),
            **init_params,
        )
    else:
        return Elasticsearch(
            url,
            api_key=ELASTIC_API_KEY,
            **init_params,
        )
```

2024-03-07 13:53 UTC, KShivendu commented on engine/clients/elasticsearch/config.py
> +    client: Elasticsearch = None
```suggestion
```

2024-04-04 10:07 UTC, filipecosta90 commented
> Thanks again for the PR! However, I'm not sure if we want to bother about auth and API keys because we don't benchmark cloud deployments. Will think about this.

@KShivendu I've removed the API key initialization. I've also extended the configurations that can be tuned and added extra checks concerning the index status and client connection. Please revise this current version

2024-04-11 09:57 UTC, KShivendu commented
Hi @filipecosta90, I've implemented your refactor in a slightly cleaner way https://github.com/qdrant/vector-db-benchmark/pull/120

Also, I'm not sure if it makes sense to retry forcing ES into using 1 segment 30 times. Is there a simpler way to do this?

2024-04-11 10:10 UTC, closed without merging

2024-04-11 10:10 UTC, filipecosta90 commented
> Also, I'm not sure if it makes sense to retry forcing ES into using 1 segment 30 times. Is there a simpler way to do this?

we can wrap it around a backoff. but lets close this PR, merge your changes and then if needed I can open a 2nd iteration PR with further changes.